#!/usr/bin/perl -w
#
# Script to read a list of off-x_2_biana.ids and also a list of job_session_2_biana.ids and if finished
# run retrieve.job(job.id, n.top = NULL, fetch.files = F, output.dir = NULL) in the guildifyR package

# INPUTS
my $session2bianaid = $ARGV[0];

# PATHS
my $Rscriptdir = "/home/quim/PHD/Projects/GUILDify/drug_repurposing/RScripts_retrieve";


#This file is generated using this expression:
#perl -e 'while(<>){if ($_ =~ /BIANA/){@t=split; $id=$t[$#t];} if ($_ =~ /^\[1\]\s\"Job id\:/){@t=split; $t[$#t]=~s/\"$//; print $t[$#t]."\t". $id ."\n";}}' < jobs.ids.log > job_to_disease_mapping.txt

# The jobs.ids.log is generated by the STD output of create.rscript_KW.pl



# READ SESSION FILE AND CREATE DATA

open(IN, "<$session2bianaid") || die;
while(<IN>){
#5cb1635e-72a9-4c1f-bd27-75eab644aba2	 KW1
#210482fb-1917-4619-98de-8a13e4eb6993	 KW2

my @t = split;
my $Rscriptfile = $Rscriptdir ."/". $t[1] .".R";
if (-e $Rscriptfile){ # Skip if present
	print $Rscriptfile . " skipped as R.script is present\n";
	next;
}

# Create Rscript
create_Rscript_retrieve($Rscriptfile, $t[0]);
system "Rscript $Rscriptfile";
}

close(IN);

exit;

########## SUBRUTINES FROM NOW -------------------------------------------------------------------------------------------

sub create_Rscript_retrieve {

my ($lfile, $lid) = @_; 

open(TMP, ">$lfile") || die "Cannot open $lfile\n";
print TMP qq[library(guildifyR)\n];
print TMP qq[retrieve.job("$lid", n.top = NULL, fetch.files = F, output.dir = NULL)\n];

close(TMP);


}


###################################################################################


